### ISSUE TITLE
Can we validate new collection names when added?

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-build-data#75]
A recently added collection name for Ansible 5 was mispelled and took a bit to figure out why the docs builds were failing. 
(well, would have taken less time had I looked at the full log, but anyway).  

It would be nice if we could add something to CI the new additions/versions to make sure they exist before the PR is merged.

(the problem was infoblox was spelled infobox.).

**Comment by dmsimard** [comment]
Thanks for the issue @samccann !

We have a github action that runs for every PR in the antsibull repo in order to test that we can still build the ansible community package: https://github.com/ansible-community/antsibull/blob/main/.github/workflows/antsibull-build.yml

We should be able to adapt it in order to run it here as well.
